<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products"> <?php echo $this->getToolbarHtml() ?>
  <?php // List mode ?>
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <?php // Product Image ?>
        <?php
        $estimated = "";
        $pyavsku = $_product->getSku();
        if(!$_product->isSaleable()) {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/estimates.png" style="margin:0px 0 0 0px;height:165px;width:165px;"></div>
        <? }
        $pyavsku = substr($pyavsku, 0, 2);
        if (($pyavsku == 'MP')||($pyavsku == 'BA')||($pyavsku == 'AE')||($pyavsku == 'AW')||($pyavsku == 'SA')||($pyavsku == 'SW')||($pyavsku == 'KW')||($pyavsku == 'WW')||($pyavsku == 'CR')||($pyavsku == 'JP')||($pyavsku == 'JA')||($pyavsku == 'JW')){ ?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/craft-logo_v.gif" style="margin:0px 0 0 0px;height:95px;width:18px;"></div>
        <?php } elseif ($pyavsku == 'NF') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/norfin-logo_v.gif" style="margin:0px 0 0 0px;height:95px;width:31px;"></div>
        <?php } elseif ($pyavsku == 'SV') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/media/wysiwyg/polarico.png" style="margin:0px 0 0 0px;"></div>
        <?php } ?>
      <div class="list-inner"> <a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="pr-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(165); ?>" width="165" height="165" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a></div>
      <?php // Product description ?>
      <div class="product-shop">
        <div class="f-fix">
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <h2 class="product-name"><a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
          <div class="desc std"> <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> <a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a> </div>
        <div class="wrapper1">  <?php echo $this->getPriceHtml($_product, true) ?>
          <?php if($_product->isSaleable()): ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
          <div class="row-list">
            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
            <?php } else { ?>
            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
            <?php }  ?>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
              <?php if ($this->helper('wishlist')->isAllow()) : ?>
              <li><a rel="nofollow" href="#" title="<?php echo $this->__('Add to Wishlist') ?>" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist tooltips"><?php echo $this->__('Add to Wishlist') ?></a></li>
              <?php endif; ?>
              <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
              <li><span class="separator">|</span> <a rel="nofollow" href="#" title="<?php echo $this->__('Add to Compare') ?>" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare tooltips"><?php echo $this->__('Add to Compare') ?></a>
                <div id="results"></div>
              </li>
              <?php endif; ?>
            </ul>
            <span id='ajax_loading<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>
          </div> <!--added -->
          </div>
        </div>
        
    </li>
    <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  <?php // Grid Mode ?>
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $_columnCount = $this->getColumnCount(); ?>
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid">
    <?php endif ?>
    <li itemscope itemtype="http://schema.org/Product" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        <?php
        $pyavsku = $_product->getSku();
        $pyavsku = substr($pyavsku, 0, 2);
        if(!$_product->isSaleable()) {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/estimates.png" style="margin:0px 0 0 0px;height:165px;width:165px;"></div>
        <? }
        if (($pyavsku == 'MP')||($pyavsku == 'BA')||($pyavsku == 'AE')||($pyavsku == 'AW')||($pyavsku == 'SA')||($pyavsku == 'SW')||($pyavsku == 'KW')||($pyavsku == 'WW')||($pyavsku == 'CR')||($pyavsku == 'JP')||($pyavsku == 'JA')||($pyavsku == 'JW')){ ?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/craft-logo_v.gif" style="margin:0px 0 0 0px;height:95px;width:18px;"></div>
        <?php } elseif ($pyavsku == 'NF') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/norfin-logo_v.gif" style="margin:0px 0 0 0px;height:95px;width:31px;"></div>
        <?php } elseif ($pyavsku == 'SV') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/media/wysiwyg/polarico.png" style="margin:0px 0 0 0px;"></div>
        <?php } ?>
      <div class="grid-inner"> <a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img itemprop="image" class="pr-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(165); ?>" width="165" height="165" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a> 
    </div>
       <h2 class="product-name product-name-height"><a itemprop="url" rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span></a></h2>
      <div class="product-box-2"> 
         <a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><div class="product-atr-height">
             <?php echo $this->getPriceHtml($_product, true) ?> 
         </div></a>
      </div>
    </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif ?>
  <?php endforeach ?>
  <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
</div>
<?php endif; ?>

<script type="text/javascript">
jQuery(document).ready(function() {
 var vmcartck = jQuery('.top-link-cart');
 vmcartck.top = vmcartck.offset().top;
 vmcartck.left = vmcartck.offset().left;
 jQuery('.btn-cart').click(function() {
   var el = jQuery(this);
   var imgtodrag = jQuery('.rwerwe:first');
   if (!imgtodrag.length) {
    elparent = el.parent();
    while (!elparent.hasClass('item')) {
     elparent = elparent.parent();
    } 
    imgtodrag = elparent.find('img.pr-img');
   }
   if (imgtodrag.length) {
    var imgclone = imgtodrag.clone()
     .offset({ top: imgtodrag.offset().top, left: imgtodrag.offset().left })
  .css({'opacity': '0.7', 'position': 'absolute' , 'height':'150px' , 'width': '150px','z-index': '1000'})
     .appendTo(jQuery('body'))
     .animate({
      'top': vmcartck.top+10,
      'left': vmcartck.left+30,
      'width':55,
      'height':55
     },1000, 'linear');
    imgclone.animate({
     'width': 0,
     'height': 0
    });
   }
 });  
    var maxHeight = 0;
    function setHeight(column) {
        column = jQuery(column);
        column.each(function() {       
            if(jQuery(this).height() > maxHeight) {
                maxHeight = jQuery(this).height();;
            }
        });
        column.height(maxHeight);
    }
    setHeight('.product-name-height');
    setHeight('.product-atr-height');
    
});
</script>