<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div>
                </div>
            <?php endif;?>
            <div class="SKU" style="margin-bottom:10px;"><?php echo $this->__('SKU')." : ".$_product->getSku() ?></div>
            <?php //echo $this->getChildHtml('alert_urls') ?>
            <?php if ($_SERVER['REMOTE_ADDR'] == "87.76.239.181") { echo $this->getChildHtml('product_type_data'); } ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>
    

            


            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>  
<!--
            <div class="row-product">
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            
            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

        </div>
-->
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
        </div>

        <div class="product-img-box">

        <?php
        $pyavsku = $_product->getSku();
        $pyav_tmp1 = explode("_", $pyavsku);
        $pyav_sku = $pyav_tmp1[1];
        $pyavsku = substr($pyavsku, 0, 2);
        if(!$_product->isSaleable()) {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/estimates.png" style="margin:70px 0 0 70px;height:165px;width:165px;"></div>
        <? }
        if (($pyavsku == 'MP')||($pyavsku == 'BA')||($pyavsku == 'AE')||($pyavsku == 'AW')||($pyavsku == 'SA')||($pyavsku == 'SW')||($pyavsku == 'KW')||($pyavsku == 'WW')||($pyavsku == 'CR')||($pyavsku == 'JP')||($pyavsku == 'JA')||($pyavsku == 'JW')){ ?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/craft-logo_v.gif" style="margin:10px 0 0 10px;height:95px;width:18px;"></div>
        <?php } elseif ($pyavsku == 'NF') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/norfin-logo_v.gif" style="margin:10px 0 0 10px;height:95px;width:31px;"></div>
        <?php } elseif ($pyavsku == 'SV') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/media/wysiwyg/polarico.png" style="margin:10px 0 0 10px;"></div>
        <?php } ?>
          <div>
            <?php echo $this->getChildHtml('media') ?>
          </div>
<!--          <div class="addthis_native_toolbox"><img src="http://craftwear.com.ua/likea.jpg" style="margin-bottom:10px;"></div>-->
<!--          <div style="align:left;">
            <div class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                <a class="addthis_button_tweet"></a>
                <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
                <a class="addthis_counter addthis_pill_style"></a>
            </div>
            <div class="row-product" style="border-bottom:0px;" class="P3">
              <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
              <?php if ($this->canEmailToFriend()): ?>
              <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
              <?php endif; ?>
            </div>
          </div> -->
        </div>
        <?php /* if (($pyav_sku == '1901654')or($pyav_sku == '1900262')) { ?>
        <div><a rel="nofollow" href="http://craftwear.com.ua/socks.html"><img src="http://craftwear.com.ua/skin/frontend/default/theme392/images/1plus1.png" style="background-color:#ffffff;"></a></div>
        <?php }
        else if (($pyav_sku == '1901653')or($pyav_sku == '193898')or($pyav_sku == '1900251'))
        { ?>
        <div><a rel="nofollow" href="http://craftwear.com.ua/socks.html"><img src="http://craftwear.com.ua/skin/frontend/default/theme392/images/1plus1w.png" style="background-color:#ffffff;"></a></div>
        <?php 
        }*/ ?>
        <?php if (($pyav_sku == '1901654')or($pyav_sku == '1900262')) { ?>
        <div style="margin-top:10px;"><a rel="nofollow" href="http://craftwear.com.ua/layer1-man/layer1-man-packs.html"><img src="http://craftwear.com.ua/skin/frontend/default/theme392/images/lookmore.jpg" style="background-color:#ffffff;"></a></div>
        <?php }
        else if (($pyav_sku == '1901653')or($pyav_sku == '193898')or($pyav_sku == '1900251'))
        { ?>
        <div style="margin-top:10px;"><a rel="nofollow" href="http://craftwear.com.ua/layer1-woman/woman-pack.html"><img src="http://craftwear.com.ua/skin/frontend/default/theme392/images/lookmore.jpg" style="background-color:#ffffff;"></a></div>
        <?php 
        } ?>
        <div class="clearer"></div>
        
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;
            if (url) {
                form.action = url;
            }
            var e = null;
            // Start of our new ajax code
            if (!url) {
                url = jQuery('#product_addtocart_form').attr('action');
            }
            url = url.replace("checkout/cart","ajax/index"); // New Code
            var data = jQuery('#product_addtocart_form').serialize();
            data += '&isAjax=1';
            jQuery('#ajax_loader').show();
            try {
                jQuery.ajax( {
                    url : url,
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(data) {
                        jQuery('#ajax_loader').hide();
                        if(data.status == 'ERROR'){
                                            jQuery('body').append('<div class="alert"></div>');
                        jQuery('.alert').slideDown(400);
                                jQuery('.alert').html(data.message).append('<button></button>');
                jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });    
                    jQuery('.alert').slideDown('400',function(){
                                        setTimeout(function(){
                                            jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
                                        },7000)
                                     });
                        }else{
                                                    jQuery('body').append('<div class="alert"></div>');
                        jQuery('.alert').slideDown(400);
                                    jQuery('.alert').html(data.message).append('<button></button>');
                                    jQuery('.alert').html(data.message).wrapInner('<a class="alert-link" href="<?php echo $this->getUrl('checkout/cart') ?>"></a>');
                jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });    
                    jQuery('.alert').slideDown('400',function(){
                                        setTimeout(function(){
                                            jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
                                        },7000)
                                     });
 
                            if(jQuery('.block-cart')){
                                jQuery('.block-cart').replaceWith(data.sidebar);
                            }
                            if(jQuery('.header .links')){
                                jQuery('.header .links').replaceWith(data.toplink);
                            }
                                        if(jQuery('.block-cart-header')){
                jQuery('.block-cart-header').replaceWith(data.sidebar_header);
            }
                        }
                    }
                });
            } catch (e) {
            }
            // End of our new ajax code
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
        }
    }.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
       
        <?php echo $this->getChildHtml('product_additional_data') ?>
        
        <?php $attStuff= $_product->getData(); ?>
        <?php if( !empty( $attStuff['videoid'] ) ): ?>        
        <div class="video">
             <p><span>Video review of:</span> Lorem ipsum dolor sit amet conse ctetur adipisicing elit</p>
             <iframe src="<?php echo $attStuff['videoid']; ?>" frameborder="0" allowfullscreen></iframe>
        </div>
        <?php endif; ?>
         
    </div>
</div><?php echo $this->getChildHtml('upsell_products') ?>
