<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
    <div class="block">
        <div class="block-title">
            <strong><span><?php echo $this->__('Sale Products') ?></span></strong>
        </div>
        <div class="block-content" style="background:url('sale_snow.jpg');">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>

                <li class="item">
        <?php
        $pyavsku = $_product->getSku();
        $pyavsku = substr($pyavsku, 0, 2);
        if (($pyavsku == 'MP')||($pyavsku == 'BA')||($pyavsku == 'AE')||($pyavsku == 'AW')||($pyavsku == 'SA')||($pyavsku == 'SW')||($pyavsku == 'KW')||($pyavsku == 'WW')||($pyavsku == 'CR')||($pyavsku == 'JP')||($pyavsku == 'JA')||($pyavsku == 'JW')){ ?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/craft-logo_v.gif" style="margin:10px 0 0 10px;height:95px;width:18px;"></div>
        <?php } elseif ($pyavsku == 'NF') {?>
        <div style="position:absolute;z-index:999;"><img src="http://craftwear.com.ua/norfin-logo_v.gif" style="margin:10px 0 0 10px;height:95px;width:31px;"></div>
        <?php } ?>

                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(165) ?>" width="165" height="165" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <div class="desc std"> 
                            <?php $small_description = strip_tags( $_product->getShortDescription());
                               if (strlen($small_description) < '50') echo($small_description);
                                  else {
                                    echo substr($small_description, 0, 55);
                                    echo '...';
                               }
                            ?> 
                        </div>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif; ?>
