<?php /** @var Mage_Core_Block_Template $this */ ?>
<?php
	/** @var Df_Qa_Model_Message_Failure $model */
	$model = $this->getData(Df_Qa_Model_Message_Failure::BLOCK_PARAM__MODEL);
	df_assert($model instanceof Df_Qa_Model_Message_Failure);
	/** @var string $currentUrl */
    $currentUrl = df_current_url();
	/** @var string $magentoVersion */
	$magentoVersion = rm_version_full();
	/** @var string $phpVersion */
	$phpVersion = phpversion();
	/** @var string $failureMessage */
	$failureMessage =
		df_trim(
			Df_Core_Model_Output_Xml::s()->outputPlain($model->getFailureMessage())
		)
	;
	/** @var string $traceAsText */
	$traceAsText = $model->getTraceAsText();
	/** @var string $rmTime */
	$rmTime = df()->date()->nowInMoscowAsText();
	/** @var string $additionalContext */
	$additionalContext = Df_Qa_Model_Context::s()->render();
	/** @var bool $isFrontend */
	$isFrontend = !df_is_admin();
	if ($isFrontend) {
		/** @var string $rmDesignPackage */
		$rmDesignPackage = rm_design_package()->getPackageName();
		/** @var string $rmDesignTheme */
		$rmDesignTheme = rm_design_package()->getTheme('default');
		if (!$rmDesignTheme) {
			$rmDesignTheme = Mage_Core_Model_Design_Package::DEFAULT_THEME;
		}
	}
echo <<<TEXT
URL:                 {$currentUrl}
Версия Magento:      {$magentoVersion}
Версия PHP:          {$phpVersion}
Время:               {$rmTime}{$additionalContext}
TEXT;
if ($isFrontend) {
	echo "\nОформительская тема: {$rmDesignPackage} / {$rmDesignTheme}\n";
}
echo <<<TEXT
***********************************
{$failureMessage}
***********************************
{$traceAsText}
TEXT;
