<?php if ($this->getItemsCount() && ($this->noCheckValues() || count($this->getValues()))): ?>
<div class="filter-<?php echo $this->getVar()?>">
 <div class="filter-name">
            <span id="filter-<?php echo $this->getVar()?>" class="<?php if($this->getIsHidden()) :?>filter-hidden-value<?php endif?>"><?php echo $this->__($this->getName()); ?></span>
        </div>
        <div class="clearer"></div>
        <div class="filter-values <?php if($this->getViewAll()):?>af-arrow-ud<?php endif;?>" id="filter-<?php echo $this->getVar()?>-value">
<ol>
    <li class="af-price-input <?php if(!$this->getInputFields()):?>no-display<?php endif;?>">
    <span><?php echo $this->__('From:');?></span>
    <input class="input-text" type="text" maxlength="10" size="3" id="nav-slider-price-from" value="<?php echo $this->getPricePangeFrom()?>" name="nav-slider-price-from"/>
    <span class="nav-separator"><?php echo $this->__('To:');?></span>
    <input class="input-text" type="text" maxlength="10" size="3" id="nav-slider-price-to" value="<?php echo $this->getPricePangeTo()?>" name="nav-slider-price-to"/>
    <?php echo $this->getSymbol();?>
    </li>
    <?php if($this->getSlider()):?>
    <li class="af-price-slider">
    	<div class="nav-slider" id="slider-range"></div>    	
    </li>
    <li class="af-price-range">
    <span class="af-price-range-left">
    <?php echo $this->getStartPangeFrom()?>
    </span>
    <span class="af-price-range-right">
    <?php echo $this->getStartPangeTo()?>
    </span>
    <div class="clearer"></div>
    </li>
    <?php endif;?>
</ol>
</div>
</div>
<script type="text/javascript">
	jQuery(function() {
		jQuery( "#slider-range" ).slider({
			range: true,
			step: <?php echo $this->getStep(); ?>,
			min: <?php echo $this->getStartPangeFrom()?>,
			max: <?php echo $this->getStartPangeTo()?>,
			values: [ <?php echo $this->getPricePangeFrom()?>, <?php echo $this->getPricePangeTo()?> ],
			slide: function( event, ui ) {
				jQuery( "#nav-slider-price-from" ).val( ui.values[ 0 ]);
				jQuery( "#nav-slider-price-to" ).val( ui.values[ 1 ]);
				<?php if(!$this->getInputFields()): ?>
				jQuery( "#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").html(ui.values[ 0 ] );
				var pos = jQuery( "#slider-range .af-first-handle" ).position();
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10}).show();
				jQuery( "#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").html( ui.values[ 1 ]);
				var pos = jQuery( "#slider-range .af-last-handle" ).position();
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10}).show();
				<?php endif;?>
			},
			create: function(event, ui) { 
				jQuery("#slider-range a.ui-slider-handle:first").addClass("af-first-handle");
				jQuery("#slider-range a.ui-slider-handle:last").addClass("af-last-handle");
				<?php if(!$this->getInputFields()): ?>
				jQuery("#slider-range").append("<div class='slider-value no-display' id='nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip'></div><div class='slider-value no-display' id='nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip'></div>");
                <?php endif;?>	
				}
		});	

		jQuery("#nav-slider-price-from").change( function(){
			var sl_min = jQuery("#nav-slider-price-from").val();
			var sl_max = jQuery("#nav-slider-price-to").val();
			jQuery( "#slider-range" ).slider( "option", "values", [sl_min,sl_max] );
			setChangePrice();
			var pos = jQuery(this).position();
			getFilterData(pos.top, pos.left);
		});
		jQuery("#nav-slider-price-to").change( function(){
			var sl_min = jQuery("#nav-slider-price-from").val();
			var sl_max = jQuery("#nav-slider-price-to").val();
			jQuery( "#slider-range" ).slider( "option", "values", [sl_min,sl_max] );
			setChangePrice();
			var pos = jQuery(this).position();
			getFilterData(pos.top, pos.left);
		});	
		jQuery( "#slider-range" ).bind( "slidestop", function(event, ui) {
			setChangePrice();
			var pos = jQuery(this).position();
			getFilterData(pos.top, pos.left);
			});	
		<?php if(!$this->getInputFields()): ?>
		jQuery( "#slider-range" ).bind( "mouseenter", function(event, ui) {
			if(jQuery( "#nav-slider-price-from").val().length)
			{
				var pos = jQuery( "#slider-range .af-first-handle" ).position();
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				var pos = jQuery( "#slider-range .af-last-handle" ).position();
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").show();
			}
			if(jQuery( "#nav-slider-price-to").val().length)
			{
				var pos = jQuery( "#slider-range .af-first-handle" ).position();
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				var pos = jQuery( "#slider-range .af-last-handle" ).position();
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").show();
			}			
			});	
		jQuery( "#slider-range" ).bind( "mousemove", function(event, ui) {
			if(jQuery( "#nav-slider-price-from").val().length)
			{
				var pos = jQuery( "#slider-range .af-first-handle" ).position();
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				var pos = jQuery( "#slider-range .af-last-handle" ).position();
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").show();
			}
			if(jQuery( "#nav-slider-price-to").val().length)
			{
				var pos = jQuery( "#slider-range .af-first-handle" ).position();
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				var pos = jQuery( "#slider-range> .af-last-handle" ).position();
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").css({"left": pos.left - 10});
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").show();
			}			
			});
		jQuery( "#slider-range" ).bind( "mouseleave", function(event, ui) {
			if(jQuery( "#nav-slider-price-from").val().length)
			{
				jQuery("#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").hide();
			}
			if(jQuery( "#nav-slider-price-to").val().length)
			{
				jQuery("#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").hide();
			}			
			});	
		jQuery(function (){
			jQuery( "#nav-decimal-from-<?php echo $this->getHtmlId(); ?>-tooltip").html(jQuery( "#nav-slider-price-from").val());
			jQuery( "#nav-decimal-to-<?php echo $this->getHtmlId(); ?>-tooltip").html(jQuery( "#nav-slider-price-to").val());
			});
		<?php endif;?>				
	});
</script>
<?php endif;?>